# Generated by Django 2.0.10 on 2019-01-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
